@startuml
start
:汉字分类;
if (中国古字或俗字?) then (yes)
    if (判定为中国古字或俗字?) then (yes)
        :①按中国汉字读音;
        :例如: "俣"是中国古字, 读yǔ, \n"搾"是中国汉字"榨"的异体字, 读zhà;
    else (no)
        :②形声文字或会意兼形声部分的读音;
        :例如: "籾"按形声字处理, 取rèn（刃）音;
    endif
elseif (中日同形字?) then (yes)
    if (中国汉字有读音?) then (yes)
        :③取同形的中国汉字读音;
        :例如: "匂"与中国汉字"匀"的早期字形相同, 取yún音,\n "槇"与中国汉字"槙"的旧字形相同, 取zhēn音;
    else (no)
        :④形声文字或会意兼形声部分的读音;
        :例如: "杣"可视为形声字, 取shān（山）音;
    endif
elseif (日本异体字?) then (yes)
    if (形似?) then (yes)
        :⑤字形类似的字读音;
        :例如: "髙"（"高"的异体字）读gāo;
    else (no)
        :⑥形声文字或会意兼形声部分的读音;
        :例如: "椿"（つばき）读chūn, \n "堓"（岸）读àn;
    endif
elseif (日本略字/俗字?) then (yes)
    if (日本简体字的繁体字与中国简体字的繁体字相同?) then (yes)
        :⑦按相应的中国简化字读音;
        :例如: "広"（日）与"广"（中）的繁体字同为"廣", 读"广（guǎng）"音,\n "桜"（日）与"樱"（中）的繁体字同为"櫻", 读"樱（yīng）"音;
    else (no)
        :⑧按相应的日本繁体字读音;
        :例如: "拂"日本简化为"払", 中国未简化, "払"读"拂（fú）"音,\n "醉"日本简化为"酔", 中国未简化, "酔"读"醉（zuì）"音;
    endif
elseif (日本合字?) then (yes)
    :例: ⑨"𢌽"取涅槃的拼音"nièpán", \n "𱁬"取䨺龘（たいと）的拼音"dduìdá";
elseif (日本自造汉字?) then (yes)
    if (形声或会意兼形声?) then (yes)
        :⑩形声文字或会意兼形声部分的读音;
        :例如: "畑"取tián（田）音, \n "辻"取shí（十）音, \n "込"取rù（入）音, \n "鴫"取tián（田）音;
    else (no)
        if (中国常用字中有类似的字?) then (yes)
            :⑪取形似字或部首的读音;
            :例如: "麿"取形似字"磨"的读音mó, \n "峠"右边的部分与"卡"相似, 取kǎ音;
        elseif (中国有相似意义的字?) then (yes)
            :⑫取相似意义的字的读音;
            :例如: "𭬺(巣籠もり)"取与其意义相近的"蛰"的拼音zhé;
        elseif (是英文单词的汉字化?) then (yes)
            :⑬取类似字形或部首的读音;
            :例如: "𫡷(ヘクタール)"取英文hectare的拼音hectare;
        endif
    endif
elseif (朝鲜汉字/古壮字/字喃?) then (yes)
    :⑭此次忽略;
endif
stop
@enduml