@startuml
start
:漢字の分類;
if (中国の古字や俗字と判断できる?\n(GKX:康熙字典等)) then (yes)
    if (中国の漢字の読み方がある?) then (yes)
        :①中国の漢字の読み方に従う;
        :例: 「俣」は中国の古字で, yǔと読む, \n「搾」は中国の漢字「榨」の異体字で, zhàと読む;
    else (no)
        :②形声文字や会意文字とみなせる部分の読み方を採用;
        :例: 「籾」は形声文字として扱い, rèn（刃）の音を取る;
    endif
elseif (日中で意味は違うが字形が同じ漢字?\n(字形の成り立ちが同じものも含む)) then (yes)
    if (中国の漢字に読み方がある?) then (yes)
        :③同じ字形の中国の漢字の読みをそのまま採用;
        :例: 「匂」は中国の漢字「匀」の古い字形と同じなので, yúnの音を取る,\n 　 「槇」は中国の漢字「槙」の旧字体と同じなので, zhēnの音を取る;
    else (no)
        :④形声文字や会意文字とみなせる部分の読み方を採用;
        :例: 「杣」は形声文字とみなせるので, shān（山）の音を取る;
    endif
elseif (日本の異体字?\n(JK:今昔文字鏡,JMJ:文字情報基盤整備事業/\n異體字字典/汉字海に異体字と載っているが中国側に詳細が無い場合)) then (yes)
    if (見た目が似ている?) then (yes)
        :⑤字形が類似する文字を採用;
        :例：「髙」（「高」の異体字）はgāoと読む;
    else (no)
        :⑥形声文字や会意文字とみなせる部分の読み方を採用;
        :例：「椿」（つばき）はchūnと読む
        　　「堓」は「岸」で, ànの音を取る;
    endif
elseif (日本の略字/俗字?) then (yes)
    if (日本の簡体字の繁体字と中国の簡体字の繁体字が同じ?) then (yes)
        :⑦対応する中国の簡体字の読みを採用;
        :例: 「広」（日）と「广」（中）の繁体字は「廣」で同じなので, 「广（guǎng）」の読みを取る
        　　「桜」（日）と「樱」（中）の繁体字は「櫻」で同じなので, 「樱（yīng）」の読みを取る;
    else (no)
        :⑧対応する日本の繁体字の読みを採用;
        :例: 「拂」は日本で「払」に簡略化されるが中国では簡略化されないので, 「払」は「拂（fú）」の読みを取る
        　　「醉」は日本で「酔」に簡略化されるが中国では簡略化されないので, 「酔」は「醉（zuì）」の読みを取る;
    endif
elseif (日本の合字?) then (yes)
    :例: ⑨「𢌽」は涅槃の拼音の「nièpán」\n　　 「𱁬」は䨺龘（たいと）を拼音で読み「dduìdá」を取る;
elseif (日本で作られた漢字?) then (yes)
    if (形声文字や会意文字とみなせる?) then (yes)
        :⑩形声文字や会意文字とみなせる部分の読み方を採用;
        :例: 「畑」はtián（田）の音を取る, \n　 「辻」はshí（十）の音を取る, \n　 「込」はrù（入）の音を取る, \n　 「鴫」はtián（田）の音を取る;
    else (no)
        if (中国で一般的な漢字で似ているものがある?) then (yes)
            :⑪字形が類似する文字や部首の読み方を採用;
            :例:「麿」は字形が類似する「磨」の読みmóを取る,
            　 「峠」の右側の部分は「卡」に類似するため, kǎの音を取る;
        elseif (中国で似ている意味の漢字がある?) then (yes)
            :⑫似ている意味の漢字の読み方を採用;
            :例: 「𭬺(巣籠もり)」は「蛰(zhé)」が意味的に近いのでzhéを取る。;
        elseif (英語を漢字にしたもの?) then (yes)
            :⑬字形が類似する文字や部首の読み方を採用;
            :例: 「𫡷(ヘクタール)」は、英語のhectareを取る。;
        endif
    endif
else (no)
    if (朝鮮漢字/古壮字/字喃?) then (yes)
        :⑭今回は除外する;
    endif
endif
stop
@enduml