@startuml
start
:汉字分类;
if (日本自造汉字?) then (yes)
    if (可视为形声或会意兼形声?) then (yes)
        :取"声旁"的读音;
        :例如: "畑"取tián（田）音, \n"辻"取shí（十）音, \n"込"取rù（入）音, \n"鴫"取tián（田）音;
    else (no)
        :取形似字或形似声旁的读音;
        :例如: "麿"取形似字"磨"的字音mó, \n"峠"右边"声旁"跟"卡"形似, 取kǎ音;
    endif
elseif (中日同形字?) then (yes)
    if (中国汉字有读音?) then (yes)
        :直接取同形的中国汉字读音;
        :例如: "匂"与中国汉字"匀"的早期字形相同, 取yún音,\n "槇"与中国汉字"槙"的旧字形相同, 取zhēn音;
    else (no)
        if (可视为形声或会意兼形声?) then (yes)
            :一般取"声旁"读音;
            :例如: "杣"可视为形声字, 取shān（山）音;
        else (no)
            :另定读音;
        endif
    endif
elseif (中国古字或俗字?) then (yes)
    if (判定为中国古字或俗字?) then (yes)
        :按中国汉字读音;
        :例如: "俣"是中国古字, 读yǔ, \n"搾"是中国汉字"榨"的异体字, 读zhà;
    else (no)
        :另定读音;
        :例如: "籾"按形声字处理, 取rèn（刃）音;
    endif
elseif (日本略字（日本简体字）?) then (yes)
    if (日本简体字形的繁体与中国内地简化字形的繁体为同一汉字字形?) then (yes)
        :按相应的中国简化字读音;
        :例如: "広"（日）"广"（中）的繁体同为"廣", 读"广（guǎng）"音, \n"桜"（日）"樱"（中）的繁体同为"櫻", 读"樱（yīng）"音;
    else (no)
        :按相应的中国传承字读音;
        :例如: "拂"日本简化为"払", 中国不简, "払"读"拂（fú）"音, \n"醉"日本简化为"酔", 中国不简, "酔"读"醉（zuì）"音;
    endif
else (no)
endif
stop
@enduml